### ISSUE TITLE
Exception ERangeError in module KaM_Remake.exe at 0032372F.

### ISSUE THREAD

**Issue by AndreiCherniaev** [reyandme/kam_remake#152]
I try to build KAM using resourses from KAM r6720 but fails; 
In _KaM_Remake.inc_ I **off**
{$DEFINE USE_MAD_EXCEPT}
{$DEFINE USE_VIRTUAL_TREEVIEW}
{$DEFINE USESECUREAUTH}

```
  case TILE_MASK_KIND_USAGE[MK] of
    mkuPixel: maskCol := ($FFFFFF or (aSprites.fRXData.RGBA[maskId, straightPx] shl 24));
    mkuAlpha: maskCol := aSprites.fRXData.RGBA[maskId, straightPx];
    else      maskCol := 0; // makes compiler happy
  end;
```

What should I do?
P.S. I just get all ".\data" folder from r6720 and put instead of ".\data" folder in my KAM Rad Studio project.

![2021-05-04 22-17-13 KaM_Remake - Delphi 10 4 - KaM_Remake dproj  Running](https://user-images.githubusercontent.com/27889022/117050775-cfb46280-ad26-11eb-8d18-940a130fef1f.png)

![2021-05-04 22-26-53 KaM_Remake - Delphi 10 4 - KM_ResSprites  Stopped - Thread 10852](https://user-images.githubusercontent.com/27889022/117051803-0179f900-ad28-11eb-9909-775eea8f93c8.png)

**Comment by reyandme** [comment]
Hi,
data files from r6720 does not have newly added sprites, that's why you got an error, I suppose.
Follow this article on wiki: https://github.com/reyandme/kam_remake/wiki/ProjectCompilation

Also you can contact me (or Krom) on our discord server (we both speaks Russian, btw): https://discord.gg/UkkYceR
