### ISSUE TITLE
No sound when I KaM Remake

### ISSUE THREAD

**Issue by Lokidari** [reyandme/kam_remake#74]
Hi, first, thanks for all.
I have an issue : compiling the game and play the game work very well but I got no sound :
- OST from the game are missing
- Voice from army, and every PNJ are missing too.
Any help ?

Thanks you.

**Comment by reyandme** [comment]
Music and army voices are not presented in this repository since they have owner rights from original Knights and Merchants game. You need to buy and install orignal game, then use music/audio files from there.
Other option could be to get previous KaM Remake version (r6720) from kamremake.com

What is PNJ ?

**Comment by Lokidari** [comment]
Thanks for the answer

I copied / paste the ./Sounds folder from KaM Remake R6720 to dev and ./data/sfx folder to Dev.
